<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MCM-04801.local" failures="1" tests="5" name="Functional Test" time="8.045" errors="0" timestamp="2020-06-20T14:38:25 CEST">
  <testcase classname="com.liveintent.test.RoutingTest" name="routingTest" time="1.054">
    <skipped/>
  </testcase> <!-- routingTest -->
  <testcase classname="com.liveintent.test.RoutingTest" name="routingTest" time="0.125">
    <skipped/>
  </testcase> <!-- routingTest -->
  <testcase classname="com.liveintent.test.RoutingTest" name="routingTest" time="0.121">
    <skipped/>
  </testcase> <!-- routingTest -->
  <testcase classname="com.liveintent.test.RoutingTest" name="routingTest" time="0.121">
    <skipped/>
  </testcase> <!-- routingTest -->
  <testcase classname="com.liveintent.test.RoutingTest" name="routingTest" time="0.152">
    <failure type="java.lang.AssertionError" message="expected [bd4d86e4-a331-4a90-a183-025222f3024e] but found [03f818b2-a995-4a7c-9e13-fe99dc8307b6]">
      <![CDATA[java.lang.AssertionError: expected [bd4d86e4-a331-4a90-a183-025222f3024e] but found [03f818b2-a995-4a7c-9e13-fe99dc8307b6]
at com.liveintent.Utilities.KinesisUtil.verifyRecordAddedToCorrectStream(KinesisUtil.java:158)
at com.liveintent.test.RoutingTest.routingTest(RoutingTest.java:35)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- routingTest -->
</testsuite> <!-- Functional Test -->
